# -*- coding: utf-8 -*-

import pytest

from tfmod.api import Meta, ModuleList, ShortModule


@pytest.mark.vcr
def test_list(api_client) -> None:
    modules = api_client.list()

    assert modules == ModuleList(
        meta=Meta(
            limit=15,
            current_offset=0,
            next_offset=15,
            prev_offset=None,
            next_url="https://registry.terraform.io/v1/modules?offset=15",
        ),
        modules=[
            ShortModule(
                id="GoogleCloudPlatform/lb-http/google/12.0.0",
                owner="",
                namespace="GoogleCloudPlatform",
                name="lb-http",
                version="12.0.0",
                provider="google",
                provider_logo_url="/images/providers/google-cloud.svg",
                description="Creates a global HTTP load balancer for Compute Engine by "
                "using forwarding rules",
                source="https://github.com/terraform-google-modules/terraform-google-lb-http",
                tag="v12.0.0",
                published_at="2024-09-17T16:58:50.45639Z",
                downloads=5283932,
                verified=True,
            ),
            ShortModule(
                id="GoogleCloudPlatform/managed-instance-group/google/1.1.15",
                owner="",
                namespace="GoogleCloudPlatform",
                name="managed-instance-group",
                version="1.1.15",
                provider="google",
                provider_logo_url="/images/providers/google-cloud.svg",
                description="Modular Google Compute Engine managed instance group for "
                "Terraform.",
                source="https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group",
                tag="1.1.15",
                published_at="2019-02-14T16:55:26.567562Z",
                downloads=158959,
                verified=True,
            ),
            ShortModule(
                id="GoogleCloudPlatform/lb-internal/google/7.0.0",
                owner="",
                namespace="GoogleCloudPlatform",
                name="lb-internal",
                version="7.0.0",
                provider="google",
                provider_logo_url="/images/providers/google-cloud.svg",
                description="Creates an internal load balancer for Compute Engine by "
                "using forwarding rules",
                source="https://github.com/terraform-google-modules/terraform-google-lb-internal",
                tag="v7.0.0",
                published_at="2024-10-07T17:43:57.6009Z",
                downloads=4394190,
                verified=True,
            ),
            ShortModule(
                id="GoogleCloudPlatform/nat-gateway/google/1.2.3",
                owner="",
                namespace="GoogleCloudPlatform",
                name="nat-gateway",
                version="1.2.3",
                provider="google",
                provider_logo_url="/images/providers/google-cloud.svg",
                description="Modular NAT Gateway on Google Compute Engine for "
                "Terraform.",
                source="https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway",
                tag="v1.2.3",
                published_at="2020-02-12T16:37:09.082788Z",
                downloads=61574,
                verified=True,
            ),
            ShortModule(
                id="alibaba/ecs-instance/alicloud/2.12.0",
                owner="",
                namespace="alibaba",
                name="ecs-instance",
                version="2.12.0",
                provider="alicloud",
                provider_logo_url="/images/providers/alibaba.png?2",
                description="Terraform module which creates ECS instance(s) on Alibaba "
                "Cloud.",
                source="https://github.com/alibabacloud-automation/terraform-alicloud-ecs-instance",
                tag="v2.12.0",
                published_at="2024-08-08T11:42:47.317861Z",
                downloads=27950,
                verified=True,
            ),
            ShortModule(
                id="alibaba/slb/alicloud/2.1.0",
                owner="",
                namespace="alibaba",
                name="slb",
                version="2.1.0",
                provider="alicloud",
                provider_logo_url="/images/providers/alibaba.png?2",
                description="Terraform module which creates Load balancer and attach "
                "ECS instances in it on Alibaba Cloud.",
                source="https://github.com/alibabacloud-automation/terraform-alicloud-slb",
                tag="v2.1.0",
                published_at="2024-10-25T09:50:51.498721Z",
                downloads=4311,
                verified=True,
            ),
            ShortModule(
                id="alibaba/vpc/alicloud/1.11.0",
                owner="",
                namespace="alibaba",
                name="vpc",
                version="1.11.0",
                provider="alicloud",
                provider_logo_url="/images/providers/alibaba.png?2",
                description="Terraform module which creates VPC and Subnet resources "
                "on Alibaba Cloud.",
                source="https://github.com/alibabacloud-automation/terraform-alicloud-vpc",
                tag="v1.11.0",
                published_at="2024-09-10T09:39:55.550841Z",
                downloads=107341,
                verified=True,
            ),
            ShortModule(
                id="oracle/compute-instance/opc/1.0.1",
                owner="",
                namespace="oracle",
                name="compute-instance",
                version="1.0.1",
                provider="opc",
                provider_logo_url="/images/providers/oracle.svg",
                description="Terraform Module for creating Oracle Cloud Infrastructure "
                "OPC Compute instances",
                source="https://github.com/oracle/terraform-opc-compute-instance",
                tag="v1.0.1",
                published_at="2019-02-14T16:55:38.116329Z",
                downloads=973,
                verified=True,
            ),
            ShortModule(
                id="alibaba/security-group/alicloud/2.4.0",
                owner="",
                namespace="alibaba",
                name="security-group",
                version="2.4.0",
                provider="alicloud",
                provider_logo_url="/images/providers/alibaba.png?2",
                description="Terraform module which creates Security Group and sets "
                "rules for it on Alibaba Cloud.",
                source="https://github.com/alibabacloud-automation/terraform-alicloud-security-group",
                tag="v2.4.0",
                published_at="2021-08-29T13:02:46.663333Z",
                downloads=70734,
                verified=True,
            ),
            ShortModule(
                id="GoogleCloudPlatform/sql-db/google/23.0.0",
                owner="",
                namespace="GoogleCloudPlatform",
                name="sql-db",
                version="23.0.0",
                provider="google",
                provider_logo_url="/images/providers/google-cloud.svg",
                description="Creates a Cloud SQL database instance",
                source="https://github.com/terraform-google-modules/terraform-google-sql-db",
                tag="v23.0.0",
                published_at="2024-10-28T20:56:38.234394Z",
                downloads=11239813,
                verified=True,
            ),
            ShortModule(
                id="oracle/ip-networks/opc/1.0.0",
                owner="",
                namespace="oracle",
                name="ip-networks",
                version="1.0.0",
                provider="opc",
                provider_logo_url="/images/providers/oracle.svg",
                description="Terraform Module for creating Oracle Cloud Infrastructure "
                "OPC IP Neworks",
                source="https://github.com/oracle/terraform-opc-ip-networks",
                tag="v1.0.0",
                published_at="2019-02-14T16:56:16.669133Z",
                downloads=894,
                verified=True,
            ),
            ShortModule(
                id="GoogleCloudPlatform/lb/google/5.0.0",
                owner="",
                namespace="GoogleCloudPlatform",
                name="lb",
                version="5.0.0",
                provider="google",
                provider_logo_url="/images/providers/google-cloud.svg",
                description="Creates a regional TCP proxy load balancer for Compute "
                "Engine by using target pools and forwarding rules",
                source="https://github.com/terraform-google-modules/terraform-google-lb",
                tag="v5.0.0",
                published_at="2024-10-07T17:44:33.527429Z",
                downloads=41652,
                verified=True,
            ),
            ShortModule(
                id="terraform-alicloud-modules/slb-listener/alicloud/1.5.0",
                owner="",
                namespace="terraform-alicloud-modules",
                name="slb-listener",
                version="1.5.0",
                provider="alicloud",
                provider_logo_url="/images/providers/alibaba.png?2",
                description="A terraform module supports to create a specified load "
                "balancer listerner.",
                source="https://github.com/alibabacloud-automation/terraform-alicloud-slb-listener",
                tag="v1.5.0",
                published_at="2024-08-08T09:43:30.586294Z",
                downloads=2569,
                verified=True,
            ),
            ShortModule(
                id="terraform-alicloud-modules/kubernetes-wordpress/alicloud/1.0.1",
                owner="",
                namespace="terraform-alicloud-modules",
                name="kubernetes-wordpress",
                version="1.0.1",
                provider="alicloud",
                provider_logo_url="/images/providers/alibaba.png?2",
                description="Terraform module which deploys Wordpress and MySQL on "
                "Alibaba Cloud Kubernetes.",
                source="https://github.com/alibabacloud-automation/terraform-alicloud-kubernetes-wordpress",
                tag="v1.0.1",
                published_at="2018-09-19T09:45:39.358253Z",
                downloads=880,
                verified=True,
            ),
            ShortModule(
                id="terraform-alicloud-modules/disk/alicloud/1.5.0",
                owner="",
                namespace="terraform-alicloud-modules",
                name="disk",
                version="1.5.0",
                provider="alicloud",
                provider_logo_url="/images/providers/alibaba.png?2",
                description="Terraform module which creates ECS Disks and attach them "
                "to ECS instance on Alibaba Cloud",
                source="https://github.com/alibabacloud-automation/terraform-alicloud-disk",
                tag="v1.5.0",
                published_at="2021-12-10T07:42:49.674667Z",
                downloads=956,
                verified=True,
            ),
        ],
    )
